/* radicals.js — 学写字 · Character Studio · radical (部首) dictionary.
   Keyed by the BASE radical glyph. Gives every character a radical explanation
   for free (name + meaning + a short "what it hints at" note) without having to
   author anything per-character. The Learn page normalises a character's
   `radical` (stripping any " (…名…)" the source data tacked on) and looks it up.
   Add entries freely — anything missing just falls back to the glyph alone. */
window.RADICALS = {
  "亻":{cn:"单人旁", en:"person", note:"this character is about people or what people do"},
  "人":{cn:"人", en:"person", note:"about people"},
  "彳":{cn:"双人旁", en:"step / go", note:"to do with walking or movement"},
  "口":{cn:"口字旁", en:"mouth", note:"to do with the mouth — eating, speaking, sounds"},
  "讠":{cn:"言字旁", en:"speech", note:"about words, speaking or language"},
  "辶":{cn:"走之底", en:"walk / road", note:"about moving, going or a journey"},
  "走":{cn:"走", en:"walk / run", note:"about going on foot"},
  "足":{cn:"足字旁", en:"foot", note:"to do with the foot or legs"},
  "⻊":{cn:"足字旁", en:"foot", note:"to do with the foot or legs"},
  "扌":{cn:"提手旁", en:"hand", note:"an action done with the hand"},
  "手":{cn:"手", en:"hand", note:"to do with the hand"},
  "又":{cn:"又字旁", en:"hand", note:"a hand doing something"},
  "寸":{cn:"寸", en:"hand / measure", note:"a hand, or measuring"},
  "心":{cn:"心字底", en:"heart", note:"about feelings and the heart"},
  "忄":{cn:"竖心旁", en:"heart", note:"about feelings"},
  "目":{cn:"目字旁", en:"eye", note:"to do with the eyes or seeing"},
  "见":{cn:"见", en:"see", note:"about looking and seeing"},
  "耳":{cn:"耳字旁", en:"ear", note:"to do with the ear or hearing"},
  "页":{cn:"页字旁", en:"head / page", note:"often about the head"},
  "首":{cn:"首", en:"head", note:"about the head or being first"},
  "身":{cn:"身", en:"body", note:"about the body"},
  "月":{cn:"月字旁", en:"moon / flesh", note:"the moon, or a part of the body"},
  "肉":{cn:"肉", en:"flesh / meat", note:"about the body or meat"},
  "鼻":{cn:"鼻", en:"nose", note:"to do with the nose"},
  "牙":{cn:"牙", en:"tooth", note:"to do with teeth"},
  "女":{cn:"女字旁", en:"woman", note:"about women or family"},
  "子":{cn:"子字旁", en:"child", note:"about children"},
  "父":{cn:"父", en:"father", note:"about a parent"},
  "宀":{cn:"宝盖头", en:"roof", note:"about a house or being indoors"},
  "冖":{cn:"秃宝盖", en:"cover", note:"something covered over"},
  "广":{cn:"广字头", en:"shelter", note:"a building or shelter"},
  "厂":{cn:"厂字头", en:"cliff / shed", note:"a building against a slope"},
  "尸":{cn:"尸字头", en:"body / house", note:"often about the body or a dwelling"},
  "门":{cn:"门字框", en:"door / gate", note:"about a door or gateway"},
  "囗":{cn:"国字框", en:"enclosure", note:"something surrounded or enclosed"},
  "冂":{cn:"同字框", en:"borders", note:"an outer boundary"},
  "匚":{cn:"三框", en:"box", note:"something boxed in"},
  "木":{cn:"木字旁", en:"tree / wood", note:"about trees, plants or wood"},
  "禾":{cn:"禾木旁", en:"grain", note:"about crops and grain"},
  "艹":{cn:"草字头", en:"grass / plant", note:"about plants and grass"},
  "竹":{cn:"竹字头", en:"bamboo", note:"about bamboo"},
  "⺮":{cn:"竹字头", en:"bamboo", note:"about bamboo or things made from it"},
  "米":{cn:"米字旁", en:"rice", note:"about rice and grains"},
  "氵":{cn:"三点水", en:"water", note:"to do with water or liquid"},
  "水":{cn:"水", en:"water", note:"about water"},
  "冫":{cn:"两点水", en:"ice", note:"about cold and ice"},
  "雨":{cn:"雨字头", en:"rain", note:"about weather and rain"},
  "气":{cn:"气字头", en:"air / gas", note:"about air or breath"},
  "火":{cn:"火字旁", en:"fire", note:"about fire and heat"},
  "灬":{cn:"四点底", en:"fire", note:"fire underneath — heat or cooking"},
  "日":{cn:"日字旁", en:"sun / day", note:"about the sun, light or time"},
  "土":{cn:"土字旁", en:"earth", note:"about soil, ground or earth"},
  "山":{cn:"山", en:"mountain", note:"about mountains"},
  "石":{cn:"石字旁", en:"stone", note:"about rock and stone"},
  "田":{cn:"田字旁", en:"field", note:"about farm fields"},
  "钅":{cn:"金字旁", en:"metal", note:"about metal and tools"},
  "王":{cn:"王字旁", en:"jade / king", note:"about jade or precious things"},
  "贝":{cn:"贝字旁", en:"shell / money", note:"about money or value"},
  "里":{cn:"里", en:"village / mile", note:"a place or distance"},
  "巾":{cn:"巾字旁", en:"cloth", note:"about cloth and fabric"},
  "衤":{cn:"衣字旁", en:"clothing", note:"about clothes"},
  "衣":{cn:"衣字底", en:"clothing", note:"about clothes"},
  "纟":{cn:"绞丝旁", en:"silk / thread", note:"about thread, string or fabric"},
  "礻":{cn:"示字旁", en:"ritual / spirit", note:"about worship or blessings"},
  "马":{cn:"马字旁", en:"horse", note:"about horses"},
  "鱼":{cn:"鱼字旁", en:"fish", note:"about fish"},
  "鸟":{cn:"鸟字旁", en:"bird", note:"about birds"},
  "虫":{cn:"虫字旁", en:"insect", note:"about bugs and small creatures"},
  "飞":{cn:"飞", en:"fly", note:"about flying"},
  "犭":{cn:"反犬旁", en:"animal", note:"about animals, often four-legged"},
  "羊":{cn:"羊", en:"sheep / goat", note:"about sheep or goats"},
  "龙":{cn:"龙", en:"dragon", note:"about the dragon"},
  "舟":{cn:"舟字旁", en:"boat", note:"about boats"},
  "车":{cn:"车字旁", en:"vehicle", note:"about carts and cars"},
  "方":{cn:"方字旁", en:"square / direction", note:"about direction or banners"},
  "饣":{cn:"食字旁", en:"food / eat", note:"about food and eating"},
  "力":{cn:"力字旁", en:"strength", note:"about strength and effort"},
  "刂":{cn:"立刀旁", en:"knife", note:"about cutting"},
  "戈":{cn:"戈", en:"spear", note:"about weapons"},
  "矢":{cn:"矢", en:"arrow", note:"about arrows"},
  "攵":{cn:"反文旁", en:"tap / action", note:"an action, often with a hand"},
  "夂":{cn:"折文", en:"go / follow", note:"about following or arriving"},
  "彡":{cn:"三撇", en:"hair / pattern", note:"about lines, hair or decoration"},
  "音":{cn:"音", en:"sound", note:"about sound"},
  "文":{cn:"文", en:"writing", note:"about writing and culture"},
  "角":{cn:"角字旁", en:"horn", note:"about horns or corners"},
  "立":{cn:"立字旁", en:"stand", note:"about standing"},
  "高":{cn:"高", en:"tall", note:"about height"},
  "干":{cn:"干", en:"dry / pole", note:"a pole or dryness"},
  "阝":{cn:"耳朵旁", en:"place / mound", note:"about a place, hill or town"},
  "亠":{cn:"点横头", en:"lid", note:"a top or lid (shape clue)"},
  "八":{cn:"八字旁", en:"eight / divide", note:"about splitting apart"},
  "十":{cn:"十", en:"ten", note:"about the number ten or completeness"},
  "二":{cn:"二", en:"two", note:"about the number two"},
  "一":{cn:"一", en:"one", note:"about the number one or a single line"},
  "大":{cn:"大", en:"big", note:"about size — a person stretching wide"},
  "小":{cn:"小", en:"small", note:"about smallness"},
  "夕":{cn:"夕字旁", en:"evening", note:"about dusk and evening"},
  "乙":{cn:"乙", en:"second / hook", note:"a single hooked stroke"},
  "乛":{cn:"横钩", en:"hook", note:"a hooked stroke (shape clue)"},
  "丿":{cn:"撇", en:"slash", note:"a single sweeping stroke (shape clue)"},
  "丶":{cn:"点", en:"dot", note:"a single dot (shape clue)"},
  "丨":{cn:"竖", en:"line", note:"a single vertical stroke (shape clue)"},
  "旡":{cn:"无", en:"choke / none", note:"a rare component"},
  "⺌":{cn:"小字头", en:"small", note:"a smallness / grain clue at the top"},
  "⺼":{cn:"肉月旁", en:"flesh", note:"often a part of the body"},
  "丷":{cn:"倒八", en:"split", note:"about splitting apart (shape clue)"},
  "乚":{cn:"竖弯钩", en:"hook", note:"a single curved hook (shape clue)"},
  "亅":{cn:"竖钩", en:"hook", note:"a vertical hooked stroke (shape clue)"},
  "儿":{cn:"儿字底", en:"legs / child", note:"a person's legs, or a child"},
  "入":{cn:"入字旁", en:"enter", note:"about entering or going in"},
  "几":{cn:"几字旁", en:"small table", note:"a little table, or 'how many'"},
  "凵":{cn:"凵字框", en:"open box", note:"an open container (shape clue)"},
  "刀":{cn:"刀字旁", en:"knife", note:"about cutting or a blade"},
  "勹":{cn:"包字头", en:"wrap", note:"about wrapping something up"},
  "匸":{cn:"三框", en:"hide / box", note:"a box that hides things"},
  "卩":{cn:"单耳旁", en:"seal", note:"a kneeling person, or an official seal"},
  "厶":{cn:"私字", en:"private", note:"about something private"},
  "士":{cn:"士字旁", en:"scholar", note:"a scholar or brave man"},
  "夊":{cn:"折文", en:"go slowly", note:"walking slowly behind"},
  "尢":{cn:"尤字旁", en:"weak leg", note:"a bent or weak leg (shape clue)"},
  "川":{cn:"川字", en:"river", note:"a flowing river"},
  "工":{cn:"工字旁", en:"work", note:"about work or a tool"},
  "幺":{cn:"幺字旁", en:"tiny", note:"tiny — a little twist of thread"},
  "廴":{cn:"建之旁", en:"stride", note:"taking a long stride"},
  "廾":{cn:"弄字底", en:"two hands", note:"two hands lifting something"},
  "弋":{cn:"弋字旁", en:"dart", note:"a stake or shooting dart (shape clue)"},
  "弓":{cn:"弓字旁", en:"bow", note:"about a bow for shooting"},
  "彐":{cn:"彐字旁", en:"snout / hand", note:"a hand, or a pig's snout"},
  "户":{cn:"户字头", en:"door", note:"a single door, or a household"},
  "斗":{cn:"斗字旁", en:"dipper", note:"a measuring dipper or scoop"},
  "斤":{cn:"斤字旁", en:"axe", note:"about an axe or chopping"},
  "无":{cn:"无字", en:"none", note:"nothing, having none"},
  "曰":{cn:"曰字旁", en:"say", note:"to speak, or the sun"},
  "欠":{cn:"欠字旁", en:"yawn / lack", note:"an open mouth — lacking, owing"},
  "止":{cn:"止字旁", en:"foot / stop", note:"a foot — stopping or stepping"},
  "歹":{cn:"歹字旁", en:"death", note:"about death or something bad"},
  "殳":{cn:"殳字旁", en:"strike", note:"striking with a weapon"},
  "母":{cn:"母字", en:"mother", note:"about a mother"},
  "比":{cn:"比字", en:"compare", note:"comparing, side by side"},
  "民":{cn:"民字", en:"the people", note:"about the common people"},
  "氺":{cn:"水字底", en:"water", note:"to do with water (at the foot)"},
  "爪":{cn:"爪字头", en:"claw", note:"a claw or grasping hand"},
  "片":{cn:"片字旁", en:"slice", note:"a flat slice or board"},
  "牛":{cn:"牛字旁", en:"ox", note:"about cattle or oxen"},
  "犬":{cn:"犬字旁", en:"dog", note:"about dogs"},
  "玉":{cn:"玉字旁", en:"jade", note:"precious jade"},
  "瓦":{cn:"瓦字旁", en:"tile", note:"baked clay or roof tiles"},
  "甘":{cn:"甘字", en:"sweet", note:"a sweet taste"},
  "用":{cn:"用字", en:"use", note:"using something"},
  "疋":{cn:"疋字旁", en:"cloth / foot", note:"a bolt of cloth, or a foot"},
  "疒":{cn:"病字旁", en:"sickness", note:"about illness"},
  "白":{cn:"白字旁", en:"white", note:"the colour white"},
  "皮":{cn:"皮字旁", en:"skin", note:"skin or a hide"},
  "示":{cn:"示字旁", en:"altar", note:"about spirits, ritual or worship"},
  "禸":{cn:"禸字", en:"track", note:"an animal's track (rare)"},
  "穴":{cn:"穴宝盖", en:"cave", note:"a cave or hole"},
  "糸":{cn:"绞丝底", en:"silk", note:"about silk, thread or string"},
  "缶":{cn:"缶字旁", en:"jar", note:"a clay pot or jar"},
  "耂":{cn:"老字头", en:"old", note:"about old age (top of 老)"},
  "而":{cn:"而字", en:"beard / and", note:"a beard — borrowed for 'and'"},
  "舌":{cn:"舌字旁", en:"tongue", note:"about the tongue"},
  "舛":{cn:"舛字旁", en:"opposite feet", note:"two feet facing apart (rare)"},
  "血":{cn:"血字旁", en:"blood", note:"about blood"},
  "行":{cn:"行字旁", en:"go / road", note:"walking, or a crossroads"},
  "覀":{cn:"西字头", en:"cover", note:"a cover over the top"},
  "言":{cn:"言字旁", en:"speech", note:"about words and speaking"},
  "豕":{cn:"豕字旁", en:"pig", note:"about pigs"},
  "辛":{cn:"辛字旁", en:"bitter", note:"bitter taste, or hardship"},
  "釆":{cn:"释字旁", en:"sort apart", note:"picking and sorting apart (rare)"},
  "长":{cn:"长字旁", en:"long / grow", note:"long, or growing"},
  "隹":{cn:"隹字旁", en:"bird", note:"a short-tailed bird"},
  "青":{cn:"青字旁", en:"blue-green", note:"the colour blue-green"},
  "非":{cn:"非字旁", en:"not", note:"wrong, or 'not'"},
  "风":{cn:"风字旁", en:"wind", note:"about the wind"},
  "香":{cn:"香字旁", en:"fragrant", note:"a sweet smell"},
  "鼓":{cn:"鼓字旁", en:"drum", note:"about drums"},
  "鼠":{cn:"鼠字旁", en:"rat", note:"a rat or mouse"},
  "日字旁":{cn:"日字旁", en:"sun / day", note:"to do with the sun, daytime or time"}
};
