CHARACTER_PINYIN_ENGLISH_MAPPING_BACK = {
    "的": ["de", "Structural particle modifying nouns"],
    "说": ["shuō", "to speak; to say; to explain; to scold; to tell off; a theory (usually in compounds such as 日心说 heliocentric theory)"],
    "是": ["shì", "to be (only connecting nouns)"],
    "色": ["sè", "color"],
    "花": ["huā", "flower; blossom; also pr. [wei3]"],
    "妈": ["mā", "ma; mom; mother"],
    "马": ["mǎ", "horse; horse or cavalry piece in Chinese chess; knight in Western chess"],
    "牛": ["niú", "ox; cow; bull; (slang) awesome"],
    "羊": ["yáng", "sheep; goat"],
    "鱼": ["yú", "fish"],
    "虫": ["chóng", "lower form of animal life including insects larvae worms and similar creatures"],
    "鸟": ["niǎo", "bird; (dialect) to pay attention to; (intensifier) damned; goddam"],
    "草": ["cǎo", "grass"],
    "黄": ["huáng", "yellow; pornographic; to fall through"],
    "白": ["bái", "white; snowy; pure; bright; empty; blank; plain; clear; to make clear; in vain; gratuitous; free of charge; reactionary; anti-communist; funeral; to stare coldly; to write wrong character; to state; to explain; vernacular; spoken lines in opera"],
    "黑": ["hēi", "black; dark; sinister; secret; shady; illegal; to hide (sth) away; to vilify; (loanword) to hack (computing)"],
    "绿": ["lǜ", "green"],
    "红": ["hóng", "red; popular; revolutionary; bonus"],
    "蓝": ["lán", "blue; indigo plant"],
    "马上": ["mǎshàng", "at once; right away; immediately; on horseback (i.e. by military force)"],
    "牛奶": ["niúnǎi", "cow's milk"],
    "奶牛": ["nǎiniú", "milk cow; dairy cow"],
    "山羊": ["shānyáng", "goat; (gymnastics) small-sized vaulting horse"],
    "绵羊": ["miányáng", "sheep"],
    "钓鱼": ["diàoyú", "to fish (with line and hook); to dupe"],
    "昆虫": ["kūnchóng", "insect"],
    "小鸟": ["xiǎoniǎo", "penis (kiddie term)"],
    "明白": ["míngbái", "clear; obvious; unequivocal; to understand; to realize"],
    "绿色": ["lǜsè", "green"],
    "黄河": ["huánghé", "Yellow River or Huang He"],
    "白天": ["báitiān", "daytime; during the day; day; CL:個|个[ge4]"],
    "红色": ["hóngsè", "red (color); revolutionary"],
    "草原": ["cǎoyuán", "grassland; prairie; CL:片[pian4]"],
    "绿化": ["lǜhuà", "to make green with plants; to reforest"],
    "黑暗": ["hēiàn", "dark; darkly; darkness"],
    "蓝色": ["lánsè", "blue (color)"],
    "草案": ["cǎoàn", "draft (legislation proposal etc)"],
    "女朋友": ["nv3 peng2 you", "girl friend"],
"里": ["", "in; inside"],
"游": ["", "to swim; to travel"],
    "的": ["de", "Structural particle modifying nouns"],
    "说": ["shuō", "to speak; to say; to explain; to scold; to tell off; a theory (usually in compounds such as 日心说 heliocentric theory)"],
    "是": ["shì", "to be (only connecting nouns)"],
    "色": ["sè", "color"],
    "花": ["huā", "flower; blossom; also pr. [wei3]"],
    "妈": ["mā", "ma; mom; mother"],
    "马": ["mǎ", "horse; horse or cavalry piece in Chinese chess; knight in Western chess"],
    "牛": ["niú", "ox; cow; bull; (slang) awesome"],
    "羊": ["yáng", "sheep; goat"],
    "鱼": ["yú", "fish"],
    "虫": ["chóng", "lower form of animal life including insects larvae worms and similar creatures"],
    "鸟": ["niǎo", "bird; (dialect) to pay attention to; (intensifier) damned; goddam"],
    "草": ["cǎo", "grass"],
    "黄": ["huáng", "yellow; pornographic; to fall through"],
    "白": ["bái", "white; snowy; pure; bright; empty; blank; plain; clear; to make clear; in vain; gratuitous; free of charge; reactionary; anti-communist; funeral; to stare coldly; to write wrong character; to state; to explain; vernacular; spoken lines in opera"],
    "黑": ["hēi", "black; dark; sinister; secret; shady; illegal; to hide (sth) away; to vilify; (loanword) to hack (computing)"],
    "绿": ["lǜ", "green"],
    "红": ["hóng", "red; popular; revolutionary; bonus"],
    "蓝": ["lán", "blue; indigo plant"],
    "马上": ["mǎshàng", "at once; right away; immediately; on horseback (i.e. by military force)"],
    "牛奶": ["niúnǎi", "cow's milk"],
    "奶牛": ["nǎiniú", "milk cow; dairy cow"],
    "山羊": ["shānyáng", "goat; (gymnastics) small-sized vaulting horse"],
    "绵羊": ["miányáng", "sheep"],
    "钓鱼": ["diàoyú", "to fish (with line and hook); to dupe"],
    "昆虫": ["kūnchóng", "insect"],
    "小鸟": ["xiǎoniǎo", "penis (kiddie term)"],
    "明白": ["míngbái", "clear; obvious; unequivocal; to understand; to realize"],
    "绿色": ["lǜsè", "green"],
    "黄河": ["huánghé", "Yellow River or Huang He"],
    "白天": ["báitiān", "daytime; during the day; day; CL:個|个[ge4]"],
    "红色": ["hóngsè", "red (color); revolutionary"],
    "草原": ["cǎoyuán", "grassland; prairie; CL:片[pian4]"],
    "绿化": ["lǜhuà", "to make green with plants; to reforest"],
    "黑暗": ["hēiàn", "dark; darkly; darkness"],
    "蓝色": ["lánsè", "blue (color)"],
    "草案": ["cǎoàn", "draft (legislation proposal etc)"],
    "女朋友": ["nv3 peng2 you", "girl friend"],
    "风": ["", "wind"],
    "云": ["", "cloud"],
    "雨": ["", "to rain; to fall"],
    "雪": ["", "snow; snowfall"],
    "电": ["", "electric; electricity; electrical"],
    "天": ["", "day; sky; heaven"],
    "地": ["di4", "earth; ground; field; place; land"],
    "春": ["", "spring (time)"],
    "夏": ["", "summer"],
    "秋": ["", "autumn"],
    "冬": ["", "winter"],
    "干净": ["", "clean; neat"],
    "家庭": ["", "family; household"],
    "圆珠笔": ["", "ballpoint pen"],
    "种类": ["", "kind; type"],
    "花样": ["", "variety; way of doing thing; trick"],
    "刮风": ["", "blow wind"],
    "风格": ["", "style"],
    "云南": ["", "Yunnan Province"],
    "一场雨": ["yi1 chang2 yu3", "one rain"],
    "冰雪": ["", "ice and snow"],
    "电冰箱": ["", "refrigerator"],
    "电话": ["", "telephone"],
    "电饭锅": ["", "electric cooker"],
    "电风扇": ["", "electric fan"],
    "一天": ["", "one day"],
    "今天": ["", "today"],
    "天气": ["", "weather"],
    "晴天": ["", "sunny day"],
    "地区": ["", "district; area; region; suburb"],
    "春天": ["", "spring season"],
    "春节": ["", "Spring Festival"],
    "夏天": ["", "summer season"],
    "秋天": ["", "autumn season"],
    "冬天": ["", "winter season"],
    "我饿了": ["wo3 e4 le", "hungry"],
    "妈妈老了": ["ma1 ma lao3 le", "mum is old"],
    "下雨了": ["xia4 yu3 le", "it rains"],
    "你有女朋友了吗": ["", "do you have girl friend?"],
    "我不买了": ["wo3 bu4 mai3 le", "i will not buy it"],
    "我不回家吃饭了": ["wo3 bu4 hui2 jia1 chi1 fan4 le", "i am not coming home for dinner"],
    "每天都": ["mei3 tian1 dou1", "(do something all the time) every day"],
    "市": ["", ""],
    "各": ["", ""],
    "颜": ["", ""],
    "练": ["", ""],
    "许": ["", ""],
    "漂": ["piao4", ""],
    "尺": ["", ""],
    "刀": ["", ""],
    "支": ["", ""],
    "行": ["hang2", ""],
    "商": ["", ""],
    "鞋": ["", ""],
    "品": ["", ""],
    "制": ["", ""],
    "每": ["", ""],
    "铅": ["", ""],
    "因": ["", ""],
    "呆": ["dai1", ""],
    "难": ["nan2", ""],
    "所": ["", ""],
    "馆": ["", ""],
    "空": ["kong4", ""],
    "菜": ["", ""],
    "肉": ["", ""],
    "鲜": ["", ""],
    "青": ["", ""],
    "味": ["", ""],
    "茶": ["", ""],
    "汤": ["", ""],
    "鸡": ["", ""],
    "炒": ["", ""],
    "极": ["", ""],
    "饱": ["", ""],
    "顿": ["", ""],
    "备": ["", ""],
    "减": ["", ""],
    "肥": ["", ""],
    "旁": ["", ""],
    "操": ["", ""],
    "加": ["", ""],
    "油": ["", ""],
    "站": ["", ""],
    "阔": ["", ""],
    "速": ["", ""],
    "路": ["", ""],
    "刷": ["", ""],
    "挡": ["", ""],
    "净": ["", ""],
    "表": ["", ""],
    "数": ["shu4", ""],
    "谈": ["", ""],
    "指": ["", ""],
    "辆": ["", ""],
    "越": ["", ""],
    "骑": ["", ""],
    "川": ["", ""],
    "野": ["", ""],
    "未": ["", ""],
    "总": ["", ""],
    "得": ["dei3", ""],
    "找": ["", ""],
    "借": ["", ""],
    "行": ["xing2", ""],
    "脏": ["zang1", ""],
    "害": ["", ""],
    "轻": ["", ""],
    "您": ["", ""],
    "算": ["", ""],
    "坏": ["", ""],
    "近": ["", ""],
    "反": ["", ""],
    "扑": ["", ""],
    "逃": ["", ""],
    "半": ["", ""],
    "肚": ["", ""],
    "暗": ["", ""],
    "笨": ["", ""],
    "渴": ["", ""],
    "架": ["", ""],
    "哈": ["", ""],
    "运": ["", ""],
    "错": ["", ""],
    "准": ["", ""],
    "摘": ["", ""],
    "够": ["", ""],
    "着": ["zhao2", ""],
    "始": ["", ""],
    "终": ["", ""],
    "累": ["", ""],
    "垂": ["", ""],
    "丧": ["", ""],
    "酸": ["", ""],
    "羽": ["", ""],
    "齐": ["", ""],
    "材": ["", ""],
    "吞": ["", ""],
    "其": ["", ""],
    "并": ["", ""],
    "守": ["", ""],
    "待": ["", ""],
    "棵": ["", ""],
    "休": ["", ""],
    "息": ["", ""],
    "撞": ["", ""],
    "死": ["", ""],
    "此": ["", ""],
    "求": ["", ""],
    "剑": ["", ""],
    "赶": ["", ""],
    "急": ["", ""],
    "识": ["", ""],
    "奋": ["", ""],
    "晨": ["", ""],
    "武": ["", ""],
    "章": ["", ""],
    "慈": ["", ""],
    "线": ["", ""],
    "临": ["", ""],
    "密": ["", ""],
    "缝": ["feng2", ""],
    "恐": ["", ""],
    "迟": ["", ""],
    "归": ["", ""],
    "寸": ["", ""],
    "绝": ["", ""],
    "灭": ["", ""],
    "翁": ["", ""],
    "独": ["", ""],
    "寒": ["", ""],
    "民": ["", ""],
    "阴": ["", ""],
    "杂": ["", ""],
    "君": ["", ""],
    "应": ["", ""],
    "梅": ["", ""],
    "历": ["", ""],
    "史": ["", ""],
    "繁": ["", ""],
    "荣": ["", ""],
    "强": ["", ""],
    "侨": ["", ""],
    "集": ["", ""],
    "功": ["", ""],
    "卖": ["", ""],
    "节": ["", ""],
    "贴": ["tie1", ""],
    "舞": ["", ""],
    "重": ["chong2", ""],
    "庆": ["", ""],
    "福": ["", ""],
    "拜": ["", ""],
    "访": ["", ""],
    "载": ["", ""],
    "卫": ["", ""],
    "射": ["", ""],
    "升": ["", ""],
    "雷": ["", ""],
    "客": ["", ""],
    "旗": ["", ""],
    "币": ["", ""],
    "纪": ["", ""],
    "念": ["", ""],
    "程": ["", ""],
    "雄": ["", ""],
    "顺": ["", ""],
    "利": ["", ""],
    "勇": ["", ""],
    "曾": ["ceng2", ""],
    "除": ["", ""],
    "杀": ["", ""],
    "咬": ["", ""],
    "散": ["", ""],
    "称": ["cheng1", ""],
    "象": ["", ""],
    "官": ["", ""],
    "墙": ["", ""],
    "腿": ["", ""],
    "秤": ["", ""],
    "切": ["qie1", ""],
    "摇": ["", ""],
    "主": ["", ""],
    "沉": ["", ""],
    "赞": ["", ""],
    "男": ["", ""],
    "政": ["", ""],
    "胜": ["", ""],
    "敌": ["", ""],
    "导": ["", ""],
    "浇": ["", ""],
    "椅": ["", ""],
    "解": ["", ""],
    "题": ["", ""],
    "相": ["", ""],
    "遇": ["", ""],
    "情": ["", ""],
    "为": ["wei2", ""],
    "讨": ["", ""],
    "论": ["", ""],
    "度": ["", ""],
    "愉": ["", ""],
    "简": ["", ""],
    "单": ["", ""],
    "脾": ["", ""],
    "忘": ["", ""],
    "扰": ["", ""],
    "悄": ["", ""],
    "桌": ["", ""],
    "父": ["", ""],
    "穷": ["", ""],
    "但": ["", ""],
    "改": ["", ""],
    "留": ["", ""],
    "合": ["", ""],
    "适": ["", ""],
    "误": ["", ""],
    "检": ["", ""],
    "性": ["", ""],
    "部": ["", ""],
    "伟": ["", ""],
    "译": ["", ""],
    "演": ["", ""],
    "台": ["", ""],
    "松": ["", ""],
    "逗": ["", ""],
    "严": ["", ""],
    "引": ["", ""],
    "超": ["", ""],
    "信": ["", ""],
    "封": ["", ""],
    "城": ["", ""],
    "邮": ["", ""],
    "票": ["", ""],
    "京": ["", ""],
    "安": ["", ""],
    "广": ["", ""],
    "场": ["chang3", ""],
    "全": ["", ""],
    "平": ["", ""],
    "提": ["", ""],
    "取": ["", ""],
    "进": ["", ""],
    "孙": ["", ""],
    "由": ["", ""],
    "视": ["", ""],
    "景": ["", ""],
    "非": ["", ""],
    "陪": ["", ""],
    "愉": ["", ""],
    "美": ["", ""],
    "丽": ["", ""],
    "完": ["", ""],
    "登": ["", ""],
    "色": ["", ""],
    "岸": ["", ""],
    "岛": ["", ""],
    "沿": ["", ""],
    "座": ["", ""],
    "桥": ["", ""],
    "柱": ["", ""],
    "狮": ["", ""],
    "分": ["fen1", ""],
    "啊": ["a", ""],
    "著": ["zhu4", ""],
    "建": ["", ""],
    "求": ["", ""],
    "丰": ["", ""],
    "墙": ["", ""],
    "站": ["", ""],
    "宫": ["", ""],
    "林": ["", ""],
    "王": ["", ""],
    "厅": ["", ""],
    "些": ["", ""],
    "趣": ["", ""],
    "镜": ["", ""],
    "窗": ["", ""],
    "映": ["", ""],
    "如": ["", ""],
    "样": ["", ""],
    "香": ["", ""],
    "影": ["", ""],
    "迷": ["", ""],
    "世": ["", ""],
    "界": ["", ""],
    "筑": ["", ""],
    "殿": ["", ""],
    "内": ["", ""],
    "客": ["", ""],
    "观": ["", ""],
    "晒": ["", ""],
    "照": ["", ""],
    "处": ["", ""],
    "寻": ["", ""],
    "熟": ["", ""],
    "服": ["", ""],
    "暖": ["", ""],
    "才": ["", ""],
    "健": ["", ""],
    "康": ["", ""],
    "彩": ["", ""],
    "虹": ["", ""],
    "赞": ["", ""],
    "躲": ["", ""],
    "喝": ["", ""],
    "伯": ["", ""],
    "深": ["", ""],
    "浅": ["", ""],
    "正": ["", ""],
    "突": ["", ""],
    "该": ["", ""],
    "办": ["", ""],
    "定": ["", ""],
    "原": ["", ""],
    "既": ["", ""],
    "像": ["", ""],
    "折": ["zhe2", ""],
    "筷": ["", ""],
    "轻": ["", ""],
    "兄": ["", ""],
    "力": ["", ""],
    "捞": ["", ""],
    "晚": ["", ""],
    "群": ["", ""],
    "啦": ["", ""],
    "于": ["", ""],
    "直": ["", ""],
    "接": ["", ""],
    "挂": ["", ""],
    "伸": ["", ""],
    "刚": ["", ""],
    "碰": ["", ""],
    "抬": ["", ""],
    "玉": ["", ""],
    "夹": ["", ""],
    "另": ["", ""],
    "断": ["", ""],
    "禁": ["", ""],
    "剩": ["", ""],
    "晓": ["", ""],
    "眠": ["", ""],
    "闻": ["", ""],
    "啼": ["", ""],
    "落": ["", ""],
    "农": ["", ""],
    "当": ["dang1", ""],
    "汗": ["", ""],
    "滴": ["", ""],
    "盘": ["", ""],
    "餐": ["", ""],
    "粒": ["", ""],
    "皆": ["", ""],
    "辛": ["", ""],
    "苦": ["", ""],
    "斜": ["", ""],
    "鸣": ["", ""],
    "翠": ["", ""],
    "青": ["", ""],
    "含": ["", ""],
    "聪": ["", ""],
    "戏": ["", ""],
    "缸": ["", ""],
    "装": ["", ""],
    "吓": ["", ""],
    "哭": ["", ""],
    "惊": ["", ""],
    "慌": ["", ""],
    "法": ["", ""],
    "块": ["", ""],
    "使": ["", ""],
    "劲": ["", ""],
    "砸": ["", ""],
    "救": ["", ""],
    "调": ["tiao2", ""],
    "但": ["", ""],
    "错": ["", ""],
    "够": ["", ""],
    "总": ["", ""],
    "命": ["", ""],
    "数": ["shu3", ""],
    "空": ["kong1", ""],
    "靠": ["", ""],
    "仰": ["", ""],
    "颗": ["", ""],
    "久": ["", ""],
    "清": ["", ""],
    "连": ["", ""],
    "勺": ["", ""],
    "离": ["", ""],
    "努": ["", ""],
    "术": ["", ""],
    "油": ["", ""],
    "助": ["", ""],
    "呀": ["", ""],
    "借": ["", ""],
    "答": ["da2", ""],
    "弯": ["", ""],
    "船": ["", ""],
    "尖": ["", ""],
    "握": ["", ""],
    "毛": ["", ""],
    "箭": ["", ""],
    "圆": ["", ""],
    "串": ["", ""],
    "苹": ["", ""],
    "葡": ["", ""],
    "萄": ["tao", ""],
    "特": ["", ""],
    "虽": ["", ""],
    "整": ["", ""],
    "输": ["", ""],
    "改": ["", ""],
    "永": ["", ""],
    "言": ["", ""],
    "富": ["", ""],
    "晴": ["", ""],
    "搬": ["", ""],
    "伞": ["", ""],
    "冰": ["", ""],
    "化": ["", ""],
    "叶": ["", ""],
    "妙": ["", ""],
    "细": ["", ""],
    "察": ["", ""],
    "懂": ["", ""],
    "燕": ["", ""],
    "湿": ["", ""],
    "闷": ["", ""],
    "脚": ["", ""],
    "透": ["", ""],
    "宇": ["", ""],
    "航": ["", ""],
    "员": ["", ""],
    "次": ["", ""],
    "球": ["", ""],
    "实": ["", ""],
    "类": ["", ""],
    "梦": ["", ""],
    "号": ["hao4", ""],
    "达": ["", ""],
    "泥": ["", ""],
    "卫": ["", ""],
    "切": ["qie4", ""],
    "迎": ["", ""],
    "准": ["", ""],
    "留": ["", ""],
    "刮": ["", ""],
    "从": ["", ""],
    "自己": ["", ""],
    "问题": ["", ""],
}
