// node {
// 	echo "build"
//     echo "test"
//     echo "integration test"
// }
pipeline {
    // agent {
    //     docker {
    //         image 'maven:3.6.3'
    //     }
    // }
    agent any
    environment {
        dockerHome = tool 'myDocker'
        mavenHome = tool 'myMaven'
        PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"
    }

    stages {
        stage("Checkout") {
            steps {
                sh "docker --version"
                sh "mvn --version"
                echo "build"
                echo "$PATH"
                echo "BUILD NUMBER - $env.BUILD_NUMBER"
                echo "BUILD_ID - $env.BUILD_ID"
                echo "JOB_NAME - $env.JOB_NAME"
                echo "BUILD_TAG - $env.BUILD_TAG"
                echo "BUILD_URL - $env.BUILD_URL"
            }
        }
        stage("compile") {
            steps{
                sh "mvn clean compile"
            }

        }
        stage("test") {
            steps {
                echo "test"
                sh "mvn test"
            }
        }
        stage("integration test") {
            steps {
                echo "integration"
                sh "mvn failsafe:integration-test failsafe:verify"
            }
        }
    } 
    post {
        always {
            echo "i am awesome. run always"
        }
        success {
            echo 'i run success'
        }

    }
}