# FOR CARDS
CARD_SIDE_LENGTH = 460
CARD_GRID_COLOR = (185, 185, 185, 200)
CARD_GRID_WIDTH = 3
CHARACTER_FONT = './GB2312.ttf'
PINYIN_FONT = 'calibri'
CARD_BACKGROUND_COLOR = "white"
PINYIN_FONT_SIZE = 120
CHARACTER_FONT_SIZE = 420
CHARACTER_POSITION = ((CARD_SIDE_LENGTH - CHARACTER_FONT_SIZE) // 2, 10)
CHARACTER_COLOR = "black"
CHARACTER_IMAGE_FILE_NAME_PREFIX = "./characters_pinyin_backup/zi_"
PINYIN_IMAGE_FILE_NAME_PREFIX = "./characters_pinyin_backup/pinyin_"
CHARACTER_PINYIN_FOLDER = './practice/'
# FOR GAME
CHARACTER_IMAGES_PATH = './characters/'
FILE_NAME_PATTERN = r'''_(\d+)\.jpg'''
DISPLAY_SIZE = (1000, 900)
CARD_NUMBER = 30
CARD_COLUMN_COUNT = 5
CARD_ROW_COUNT = 6
CARD_WIDTH = DISPLAY_SIZE[0] // CARD_COLUMN_COUNT
CARD_HEIGHT = DISPLAY_SIZE[1] // CARD_ROW_COUNT
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
GRAY = (200, 200, 200)
